#CC = gcc
CFLAGS = -Wall -g
LDFLAGS =

default: parse_elf parse_exe progauthfp_ngram progauthfp_dict progauthfp_compare progauthfp_test_ngram progauthfp_test_dict

clean:
	-rm -f parse_elf parse_exe progauthfp_ngram progauthfp_dict progauthfp_compare progauthfp_test_ngram progauthfp_test_dict
